# This is a basic workflow to help you get started with Actions

name: Monitor

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          res=`curl -s https://docs.google.com/spreadsheets/d/1aXzns9mgucWf2hv0nORnFqmN6KuxNl9FTFXjIHNYeg4/gviz/tq? | grep "#N/A" | wc -l`
          if [[ $res == "1" ]]; then
              curl -X POST --data-urlencode "payload={\"text\": \"check google sheets!\"}" https://hooks.slack.com/services/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
              exit 1
          fi
